run_test_after_fit: True
lr: 5e-5
layer_lr_decay: 0.95
output_dir: '.'

# read in dataset
# batch_size: 16
# num_workers: 16
train_batch_size: 32
eval_batch_size: 64
# for dataloader
# num_workers: 4
num_workers: 0
pin_memory: True
# problem_type: "single_label_classification"
preprocessing_batch_size: 500
preprocessing_num_workers: 1